language: c
script: cmake .
compiler: gcc
python:
  - "2.7"
  - "3.4"
before_install:
  - test -n $CC && unset CC
  - test -n $CXX && unset CXX
addons:
  apt:
    packages:
      - python
      - python-dev
      - cython
install:
  - wget https://cmake.org/files/v3.7/cmake-3.7.1.tar.gz
  - tar zxf cmake-3.7.1.tar.gz
  - cd cmake-3.7.1 && ./configure && make && make install
