language: c
script: cmake
compiler: gcc
python:
  - "2.7"
  - "3.4"
sudo: required
before_install:
  - test -n $CC && unset CC
  - test -n $CXX && unset CXX
  - sudo apt-get install python python-dev python3 python3-dev
