language: c
script: $HOME/cmake-3.7.1/bin/cmake .
compiler: gcc
python:
  - "2.7"
  - "3.4"
before_install:
  - test -n $CC && unset CC
  - test -n $CXX && unset CXX
addons:
  apt:
    packages:
      - python
      - python-dev
      - cython
install:
  - bash travis/install-cmake.sh
cache:
  directories:
    - $HOME/cmake-3.7.1

